### ISSUE TITLE
「であると言えます」を指摘する際の参考URLがリンク切れになっている

### ISSUE THREAD

**Issue by HelloRusk** [textlint-ja/textlint-rule-ja-no-redundant-expression#23]
「であると言えます」が冗長であることを指摘するときに出てくる参考記事

`https://www.sekaihaasobiba.com/entry/2014/10/24/204024`

がリンク切れになっています。

一応魚拓はあります。
https://web.archive.org/web/20170608111205/http://www.sekaihaasobiba.com/entry/2014/10/24/204024

**Comment by azu** [comment]
エラーから直接記事にリンクするより
https://github.com/textlint-ja/textlint-rule-ja-no-redundant-expression#dict2 のURLを表示するようにして、READMEの方にURLを全部変更するのがいいかもしれませんね。

**Comment by 7ma7X** [comment]
確かに、いちいちリンク切れに対処するのも面倒ですし、その方法がベターですね 👍

**Comment by azu** [comment]
> エラーから直接記事にリンクするより
> https://github.com/textlint-ja/textlint-rule-ja-no-redundant-expression#dict2 のURLを表示するようにして、READMEの方にURLを全部変更するのがいいかもしれませんね。

この方針に変更したので閉じます。
